### ISSUE TITLE
Unhandled CSRFMissmatchError crashes Blitz 

### ISSUE THREAD

**Issue by lksnmnn** [blitz-js/blitz#2884]
### What is the problem?

I've updated from 0.38.5 to 0.41.1 in order to fix the CSRFMissmatchError we were seeing for users, that haven't visited for a longer time. Presumbly this error was due to browsers removing the non-http cookie at will.

While this issue seems to be fixed (we saw it once on *dev* but couldn't reproduce so far), I do see several unhandled CSRFMissmatchErrors crashing the Blitz server in the logs. I wasn't able to reproduce this myself and never had this locally running `blitz dev`.

It looks like https://github.com/blitz-js/blitz/issues/2746

### Paste all your error logs here:

```
Oct 20 19:39:18 app-dev npm[1028732]: 2021-10-20 17:39:18.672 ERROR Error while processing the request
Oct 20 19:39:18 app-dev npm[1028732]:  CSRFTokenMismatchError
Oct 20 19:39:18 app-dev npm[1028732]: details:
Oct 20 19:39:18 app-dev npm[1028732]: {
Oct 20 19:39:18 app-dev npm[1028732]:   name: 'CSRFTokenMismatchError',
Oct 20 19:39:18 app-dev npm[1028732]:   statusCode: 401
Oct 20 19:39:18 app-dev npm[1028732]: }[CSRFTokenMismatchError] { statusCode: 401 }
Oct 20 19:39:18 app-dev npm[1028732]: events.js:377
Oct 20 19:39:18 app-dev npm[1028732]:       throw er; // Unhandled 'error' event
Oct 20 19:39:18 app-dev npm[1028732]:       ^
Oct 20 19:39:18 app-dev npm[1028732]: Error [ERR_STREAM_WRITE_AFTER_END] [ERR_STREAM_WRITE_AFTER_END]: write after end
Oct 20 19:39:18 app-dev npm[1028732]:     at new NodeError (internal/errors.js:322:7)
Oct 20 19:39:18 app-dev npm[1028732]:     at writeAfterEnd (_http_outgoing.js:694:15)
Oct 20 19:39:18 app-dev npm[1028732]:     at ServerResponse.end (_http_outgoing.js:815:7)
Oct 20 19:39:18 app-dev npm[1028732]:     at ServerResponse.end (/var/www/app-dev/releases/20211018171502Z/node_modules/next/dist/compiled/compression/index.js:1:4179)
Oct 20 19:39:18 app-dev npm[1028732]:     at ServerResponse.apiRes.end (/var/www/app-dev/releases/20211018171502Z/node_modules/next/dist/server/api-utils.js:83:25)
Oct 20 19:39:18 app-dev npm[1028732]:     at sendError (/var/www/app-dev/releases/20211018171502Z/node_modules/next/dist/server/api-utils.js:490:9)
Oct 20 19:39:18 app-dev npm[1028732]:     at Object.apiResolver (/var/www/app-dev/releases/20211018171502Z/node_modules/next/dist/server/api-utils.js:127:13)
Oct 20 19:39:18 app-dev npm[1028732]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Oct 20 19:39:18 app-dev npm[1028732]:     at async Server.handleApiRequest (/var/www/app-dev/releases/20211018171502Z/node_modules/next/dist/server/next-server.js:766:9)
Oct 20 19:39:18 app-dev npm[1028732]:     at async Object.fn (/var/www/app-dev/releases/20211018171502Z/node_modules/next/dist/server/next-server.js:657:37)
Oct 20 19:39:18 app-dev npm[1028732]: Emitted 'error' event on ServerResponse instance at:
Oct 20 19:39:18 app-dev npm[1028732]:     at writeAfterEndNT (_http_outgoing.js:753:7)
Oct 20 19:39:18 app-dev npm[1028732]:     at processTicksAndRejections (internal/process/task_queues.js:83:21) {
Oct 20 19:39:18 app-dev npm[1028732]:   code: 'ERR_STREAM_WRITE_AFTER_END'
Oct 20 19:39:18 app-dev npm[1028732]: }
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR! code ELIFECYCLE
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR! errno 1
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR! app-dev@1.0.0 start: `blitz start`
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR! Exit status 1
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR!
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR! Failed at the app-dev@1.0.0 start script.
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR! A complete log of this run can be found in:
Oct 20 19:39:18 app-dev npm[1028702]: npm ERR!     /var/www/.npm/_logs/2021-10-20T17_39_18_741Z-debug.log
Oct 20 19:39:18 app-dev systemd[1]: app.service: Main process exited, code=exited, status=1/FAILURE
Oct 20 19:39:18 app-dev systemd[1]: app.service: Failed with result 'exit-code'.
Oct 20 19:39:18 app-dev systemd[1]: app.service: Scheduled restart job, restart counter is at 8.
Oct 20 19:39:18 app-dev systemd[1]: Stopped app application (nodejs).
Oct 20 19:39:19 app-dev systemd[1]: Started app application (nodejs).
Oct 20 19:39:19 app-dev npm[1028789]: > app-dev@1.0.0 start /var/www/app-dev/releases/20211018171502Z
Oct 20 19:39:19 app-dev npm[1028789]: > blitz start
Oct 20 19:39:20 app-dev npm[1028819]: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. Not exactly sure :(

### Run `blitz -v` and paste the output here:

```
Linux 5.4 | linux-x64 | Node: v14.18.1

blitz: 0.41.1 (local)

  Package manager: yarn
  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (1) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 535.87 MB / 1.89 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.1 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.15 - /usr/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 3.2.1 => 3.2.1
    blitz: 0.41.1 => 0.41.1
    prisma: 3.2.1 => 3.2.1
    react: 18.0.0-alpha-ed6c091fe-20210701 => 18.0.0-alpha-ed6c091fe-20210701
    react-dom: 18.0.0-alpha-ed6c091fe-20210701 => 18.0.0-alpha-ed6c091fe-20210701
    typescript: ~4.3 => 4.3.5
```

**Comment by flybayer** [comment]
Ok that makes sense. Thanks! Will fix

**Comment by flybayer** [comment]
Fixed in https://github.com/blitz-js/blitz/releases/tag/v0.41.2-canary.5

Note - that doesn't prevent users from seeing the CSRF error, it just prevents the server from crashing.

**Comment by lksnmnn** [comment]
Great! Thank you!
The error is correct, as long as it doesn't crash the server anymore. I will test it now :)

**Comment by kaedub** [comment]
> I do believe, that this crash occurs, when a user does not have an AntiCSRF token (Browser removed it after inactivity, previous version (!)) and then visits the new version, which then crashes (as the browser couldn't send an AntiCSRF token from local storage yet).
> 

I've actually been having this issue on my development server when trying to make a POST request to an RPC url from Insomnia. I have provided a valid antiCSRFToken on the anti-csrf header in the request but still receive this error. This may be a separate issue but I thought I'd at least bring it up.

**Comment by flybayer** [comment]
@kaedub yeah that's separate. Feel free to open an issue with steps to reproduce
